# Generated by Django 3.2.3 on 2021-05-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_details',
            new_name='user',
        ),
    ]
