# Generated by Django 3.2.3 on 2021-05-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_rename_user_details_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
