# Generated by Django 3.2.3 on 2021-05-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_project_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members_in_project',
            new_name='members',
        ),
    ]
